##################################################################################################################################
# Mensaje del desarrollador: Esta traducción fue hecha por un miembro de la comunidad. No puedo asegurar que sea 100% correcta.
# Message from developer: This translation was provided by a community member. I can't say it's 100% accurate.
##################################################################################################################################
#             ___      _   _           ___          _      _                Our plugins: https://alonsoaliaga.com/plugins
#            | _ ) ___| |_| |_ ___ _ _/ __| ___  __(_)__ _| |               Support server: https://alonsoaliaga.com/discord
#            | _ \/ -_)  _|  _/ -_) '_\__ \/ _ \/ _| / _` | |               Youtube: https://alonsoaliaga.com/play
#            |___/\___|\__|\__\___|_| |___/\___/\__|_\__,_|_|               Test server: plugins.alonsoaliaga.com
#                           by AlonsoAliaga                                 Twitch: https://alonsoaliaga.com/twitch
#          Considering donating? https://alonsoaliaga.com/donate            Thanks for using my plugin! <3
#
#           Traducción hecha por Pablete#7608 (ID:250739060589461504)
Messages:
  No-permission: "&cNo tienes permisos para hacer esto."
  No-permission-edit: "&cNo tienes permiso para editar tus redes sociales :("
  Reloaded: "&aLa configuracion ha sido recargada!"
  Invalid-player: "&cEl jugador no está en linea!"
  Invalid-player-in-database: "&cEl jugador no está registrado en el servidor!"
  Unknown-error: "&cError inesperado! Intenta de nuevo más tarde, si el problema persiste, contacta un administrador."
  Unknown-error-search-other: "&cError inesperado! Intenta de nuevo más tarde, si el problema persiste, contacta un administrador."
  No-input: "&cNo proporcionaste informacion válida. Las redes sociales no se actualizarán!"
  Please-reconnect: "&cError inesperado! Por favor vuelve a conectarte al servidor."
  Please-reconnect-other: "&cError inesperado! Dile al jugador {PLAYER} que se reconecte al servidor."
  Keys:
    None: "&cNada"
  Social:
    Title: "&8Redes Sociales: {PLAYER}"
  Remove:
    Not-linked: "&cEsta red social no esta vinculada."
    Removed: "&cHas removido esta red social."
  Placeholders:
    Value-none: "Nada"
    Status-linked: "&aVinculada"
    Status-unlinked: "&cNo vinculada"
  Help:
    Admin:
      - "&9 /bettersocial edit <jugador> &f- &bAbre el menú a un jugador"
      - "&9 /bettersocial <menu/media> <jugador> &f- &bAbre tu menú de redes sociales"
      - "&9 /bettersocial reload &f- &bRecarga la configuración"
    User:
      - "&9 /bettersocial edit &f- &bAbre el menú para editar"
      - "&9 /bettersocial menu <jugador> &f- &bAbre el menú de redes sociales de un jugador"
 
Permissions:
  Admin: "bettersocial.admin"
  #Permission to be able to open "/bettersocial edit" to edit social media.
  Edit: "none" #Example: "bettersocial.edit"
  #Permission to check others social <media. Set to "none" to disable.
  Others: "none" #Example: "bettersocial.others"
  #Permission to check offline players' social media. Set to "none" to disable.
  Offline: "bettersocial.offline"
 
Options:
  #To apply changes for aliases you must RESTART the server.
  #Plugman or similar plugins are NOT and will NEVER be supported.
  #Use /reload or restart your server.
  Aliases:
  - "social"
  #Enable only if developer asks you to do it.
  Debug-mode: false
  #Should we fill empty slots?
  Fill-empty-slots: false
  #Amount of rows the inventory will have. Minimum 1, maximum 6.
  Size: 4
  #This command will be run as the player that views the profile.
  #Set to "none" to disable command. Available placeholders:
  # {TARGET} replaced by player name (The name of the player that views the profile)
  # {PLAYER} replaced by target name (The name of the player owner of the profile)
  #This is the command that will be run when clicking back button while editing social media.
  Back-edit-command: "perfil" #Example: "profile {PLAYER}"
  #This is the command that will be run when clicking back button while viewing social media.
  Back-media-command: "profile {TARGET}" #Example: "profile {TARGET}"
  Sounds:
    #Sound when opening a player's media.
    Open: "BLOCK_SNOW_HIT"
  #This is the amount of ticks the plugin will wait before loading data.
  #Useful if your have issues with players "losing" their data on server change or reconnect.
  #Set to 0 to disable. If enabled, it's like that some plugins that send messages on join will not fetch correct data from placeholders.
  #To "fix" this use this plugin made by our team which adds messages on player join with an option to set delay.
  #We also support placeholder check to prevent message to be sent when player is in vanish mode. (Using placeholder to check if player is vanished)
  #Check our plugin on https://alonsoaliaga.com/AlonsoJoin (If available)
  Data-delay: 20
  #Saves each X amount of minutes the data modified for online players.
  #This will allow checking it form other servers. HOWEVER ITS LIMITED TO SOME MINUTES.
  #I wouldn't recommend to decrease the value lower than 15 minutes tbh.
  #Set it to 0 to disable.
  Auto-save:
    Interval: 15
 
Items:
  Player:
    #Set to -1 to disable.
    Slot: 30
    #Item added if target player IS online.
    #Supports PlaceholderAPI. Default placeholder available.
    #Placeholders will be updated for the target player.
    # {PLAYER} replaced with profile owner name.
    # {VIEWER} replaced by the name of the player viewing the profile.
    Online:
      Displayname: "&a&l{PLAYER}"
      Lore:
      - "&f➥ &7Se unio: &7%player_first_join_date%"
      - "&f➥ &7Nivel: &f%alonsolevels_level%"
      #Command that will be run if player clicks the item.
      #Placeholder available are: {PLAYER} replaced by profile owner name.
      #{VIEWER} replaced with viewer name.
      Command: "none" #Example: "tell {PLAYER} Hello!"
    #Item added if target player IS online.
    #DON'T SUPPORT PlaceholderAPI!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    #Default placeholder available.
    # {PLAYER} replaced with profile owner name.
    # {VIEWER} replaced by the name of the player viewing the profile.
    Offline:
      Displayname: "&c&l{PLAYER}"
      Lore:
      - "&7El jugador no esta conectado :("
      #Command that will be run if player clicks the item.
      #Remember player is offline so use only commands that support offline players.
      #Placeholder available are: {PLAYER} replaced by profile owner name.
      #{VIEWER} replaced with viewer name.
      Command: "none" #Example: "mail {PLAYER} Hello! I'm {VIEWER}!"
  Back:
    Material: ARROW
    Slot: 31
    Displayname: "&cAtras"
    #Placeholder available is {PLAYER} replaced by viewer name.
    # {TARGET} replaced by the name of the owner of the social media.
    #The name of the player that owns the profile.
    #Supports PlaceholderAPI if available. Information replaced by the viewer's data.
    Lore:
    - "Página anterior"
  Media:
    #Used if link is less than 32 than characters.
    Lore-short:
    - "&7Actual: &e{CURRENT}&r"
    - " "
    - "&eClick-Izquierdo para cambiar!"
    - "&eClick-Derecho para quitar!"
    - " "
    - "&cTodos podrán ver y leer"
    - "&c tu informacion."
    #Used if link is greater or equal than 32 characters.
    Lore-long:
    - "&7Actual:"
    - "&e{CURRENT}&r"
    - " "
    - "&eClick-Izquierdo para cambiar!"
    - "&eClick-Derecho para quitar!"
    - " "
    - "&cTodos podràn ver y leer"
    - "&ctu informacion."
  No-media:
    Material: GLASS_BOTTLE
    Slot: 13
    Displayname: "&cSin redes :("
    #Placeholders available {PLAYER} replaced by player name.
    #Supports PlaceholderAPI if available.
    Lore:
    - "&7{PLAYER} no tiene ninguna red social"
    - "&7vinculada a su cuenta."
  Visit:
    Available:
      Lore:
      - "&eClick para ver"
    Unavailable:
      Lore:
      - ""
      - "&cSin redes :("
  Frame:
    Color: "BLACK"
    #Only 1.14+
    Custom-model-data: 0
  conectar:
    Material: GLASS_BOTTLE
    Slot: 13
    Displayname: "&cRedes Conectadas :("
    #Placeholders available {PLAYER} replaced by player name.
    #Supports PlaceholderAPI if available.
    Lore:
    - "&7{PLAYER} no tiene ninguna red social"
    - "&7vinculada a su cuenta."
  Visit:
    Available:
      Lore:
      - "&eClick para obtener mas información"
    Unavailable:
      Lore:
      - "&cNo Vinculado :("
  Frame:
    Color: "BLACK"
    #Only 1.14+
    Custom-model-data: 0
 
Database:
  #Available types: MySQL and SQLite
  #You can use MySQL to make it global or you can use SQLite to make it local.
  #MySQL requires a server (local or external)
  #SQLite doesn't require anything, it's saved in a db file in the folder.
  Type: "MySQL"
  Table: "bettersocial"
  #If type is SQLite
  File: "database-bettersocial"
  #If type is MySQL
  Host: 127.0.0.1.0
  Port: 3306
  Database: "bettersocial"
  Username: "root"
  Password: "123456"
  #Modify this just if you know what you are doing.
  #This will be added at the end of database url (Not in SQLITE, only in MySQL).
  #Useful if you want to set useSSL or autoReconnect or any other modifier.
  Additional-url: "?useSSL=false"
  #This option has been added to prevent connection timeout.
  #Time is in minutes. Every X minutes the plugin will run a test query to keep connection alive.
  #No longer used as HikariCP was implemented.
  Keep-connection-interval: 30
  HikariCP:
    Warning:
    - "========================================================================================"
    - "You don't need to edit this text, it's ONLY displayed in config so you can read it."
    - "========================================================================================"
    - "HikariCP is experimental. Remember that only modify the following IF YOU KNOW HOW IT WORKS."
    - "You will not get support for HikariCP configurations as 1) I'm not a HikariCP advanced user"
    - "and 2) Customization depends on the owner and his knowledge level."
    - "Related to Source-properties, if you KNOW and want to add custom properties follow the format:"
    - "Source-properties:"
    - '  thePropertySelected1: "theValue1"'
    - '  thePropertySelected2: "theValue2"'
    - "[!] Remember to modify data only if you know what you are doing."
    - "Available source properties can be found here: https://alonsoaliaga.com/HikariCP-sp"
    - "Available source class names can be found here: https://alonsoaliaga.com/HikariCP-cn"
    Max-pool-size: 15
    #Set your custom source class name ONLY IF YOU KNOW WHAT IT IS.
    Custom-source-class-name: "default"
    #This is the source properties to modify your HikariCP configurations.
    #It allows you to select and specify custom configs IF YOU KNOW WHAT YOU ARE DOING.
    #Source properties can be found here: https://links.alonsoaliaga.com/HikariCP-sp
    Source-properties: []
 
Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "bettersocial.update"
  #Message to send when update is found.
  Message: "&9[BetterSocial] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
